"""Database models and session helpers."""

from jobs_automation.db.base import Base, UTCDateTime, generate_uuid, utc_now
from jobs_automation.db.models import (
    ApplicationEventModel,
    ApplicationModel,
    ApplicationPacketModel,
    ArtifactModel,
    AuditLogModel,
    CandidateProfileModel,
    CompanyModel,
    ContactModel,
    InboundMessageModel,
    InterviewModel,
    JobEvaluationModel,
    JobModel,
    JobSourceModel,
    MessageLinkModel,
    PolicyRegistryModel,
    SourceAccountModel,
    SourceAlertModel,
    TaskModel,
)
from jobs_automation.db.session import (
    check_db_connection,
    get_db,
    get_engine,
    get_sessionmaker,
    init_db,
)

__all__ = [
    "ApplicationEventModel",
    "ApplicationModel",
    "ApplicationPacketModel",
    "ArtifactModel",
    "AuditLogModel",
    "Base",
    "CandidateProfileModel",
    "CompanyModel",
    "ContactModel",
    "InboundMessageModel",
    "InterviewModel",
    "JobEvaluationModel",
    "JobModel",
    "JobSourceModel",
    "MessageLinkModel",
    "PolicyRegistryModel",
    "SourceAccountModel",
    "SourceAlertModel",
    "TaskModel",
    "UTCDateTime",
    "check_db_connection",
    "generate_uuid",
    "get_db",
    "get_engine",
    "get_sessionmaker",
    "init_db",
    "utc_now",
]
