"""v3_agent_runtime_foundation

Revision ID: 3934ce883107
Revises: 003_generation_origin_readiness
Create Date: 2026-09-23 11:08:56.428672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import jobs_automation.db.base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3934ce883107'
down_revision: Union[str, Sequence[str], None] = '003_generation_origin_readiness'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('memory_key', sa.String(length=128), nullable=False),
    sa.Column('memory_value_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_agent_id'), 'agent_memory', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_memory_memory_key'), 'agent_memory', ['memory_key'], unique=False)
    op.create_table('agent_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('assigned_agent', sa.String(length=64), nullable=True),
    sa.Column('input_artifact_refs_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('constraints_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('permission_scope', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('output_artifact_refs_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_checkpoint',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=128), nullable=False),
    sa.Column('checkpoint_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('parent_checkpoint_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_checkpoint_checkpoint_id'), 'agent_checkpoint', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_agent_checkpoint_task_id'), 'agent_checkpoint', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_checkpoint_thread_id'), 'agent_checkpoint', ['thread_id'], unique=False)
    op.create_table('agent_trace_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_trace_event_task_id'), 'agent_trace_event', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_trace_event_task_id'), table_name='agent_trace_event')
    op.drop_table('agent_trace_event')
    op.drop_index(op.f('ix_agent_checkpoint_thread_id'), table_name='agent_checkpoint')
    op.drop_index(op.f('ix_agent_checkpoint_task_id'), table_name='agent_checkpoint')
    op.drop_index(op.f('ix_agent_checkpoint_checkpoint_id'), table_name='agent_checkpoint')
    op.drop_table('agent_checkpoint')
    op.drop_table('agent_task')
    op.drop_index(op.f('ix_agent_memory_memory_key'), table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_agent_id'), table_name='agent_memory')
    op.drop_table('agent_memory')
    # ### end Alembic commands ###
