"""v23_intelligence_foundation

Revision ID: 21b2eaaa4543
Revises: 3934ce883107
Create Date: 2026-09-23 13:28:59.008299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21b2eaaa4543'
down_revision: Union[str, Sequence[str], None] = '3934ce883107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_edge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('predicate', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('inferred', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('observed_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_from', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_to', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='REVIEW_REQUIRED', nullable=False),
    sa.Column('invalidated_reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_id', 'predicate', 'object_type', 'object_id', 'source_type', 'source_reference', name='uq_opportunity_edge_evidence')
    )
    op.create_index('ix_opportunity_edge_object', 'opportunity_edge', ['object_type', 'object_id'], unique=False)
    op.create_index('ix_opportunity_edge_predicate_status', 'opportunity_edge', ['predicate', 'status'], unique=False)
    op.create_index('ix_opportunity_edge_source_reference', 'opportunity_edge', ['source_reference'], unique=False)
    op.create_index('ix_opportunity_edge_subject', 'opportunity_edge', ['subject_type', 'subject_id'], unique=False)
    op.create_table('strategy_experiment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('target_population_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metric_definition_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='DRAFT', nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('target_company',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='3', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('target_role_families', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('compensation_floor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location_constraints', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('watch_status', sa.String(length=16), server_default='PAUSED', nullable=False),
    sa.Column('source_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_index('ix_target_company_watch_status', 'target_company', ['watch_status'], unique=False)
    op.create_table('target_company_observation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_company_id', sa.Uuid(), nullable=False),
    sa.Column('observation_type', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=512), nullable=False),
    sa.Column('observed_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('normalized_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='NEW', nullable=False),
    sa.Column('created_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['target_company_id'], ['target_company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_company_id', 'dedupe_key', name='uq_target_company_observation_dedupe')
    )
    op.create_index('ix_target_company_observation_company_time', 'target_company_observation', ['target_company_id', 'observed_at'], unique=False)
    op.create_index('ix_target_company_observation_job', 'target_company_observation', ['job_id'], unique=False)
    op.create_table('strategy_experiment_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('treatment_type', sa.String(length=64), nullable=False),
    sa.Column('resume_variant_id', sa.Uuid(), nullable=True),
    sa.Column('treatment_payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('treatment_hash', sa.String(length=64), nullable=False),
    sa.Column('assigned_at', jobs_automation.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['strategy_experiment.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['resume_variant_id'], ['resume_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'job_id', name='uq_strategy_experiment_assignment_job')
    )
    op.create_index('ix_strategy_experiment_assignment_app', 'strategy_experiment_assignment', ['application_id'], unique=False)
    op.drop_constraint(op.f('inbound_message_provider_message_id_key'), 'inbound_message', type_='unique')
    op.drop_index(op.f('ix_inbound_message_provider_message_id'), table_name='inbound_message')
    op.create_index(op.f('ix_inbound_message_provider_message_id'), 'inbound_message', ['provider_message_id'], unique=True)
    op.add_column('message_link', sa.Column('contact_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_message_link_contact_id'), 'message_link', ['contact_id'], unique=False)
    op.create_foreign_key(None, 'message_link', 'contact', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'message_link', type_='foreignkey')
    op.drop_index(op.f('ix_message_link_contact_id'), table_name='message_link')
    op.drop_column('message_link', 'contact_id')
    op.drop_index(op.f('ix_inbound_message_provider_message_id'), table_name='inbound_message')
    op.create_index(op.f('ix_inbound_message_provider_message_id'), 'inbound_message', ['provider_message_id'], unique=False)
    op.create_unique_constraint(op.f('inbound_message_provider_message_id_key'), 'inbound_message', ['provider_message_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_strategy_experiment_assignment_app', table_name='strategy_experiment_assignment')
    op.drop_table('strategy_experiment_assignment')
    op.drop_index('ix_target_company_observation_job', table_name='target_company_observation')
    op.drop_index('ix_target_company_observation_company_time', table_name='target_company_observation')
    op.drop_table('target_company_observation')
    op.drop_index('ix_target_company_watch_status', table_name='target_company')
    op.drop_table('target_company')
    op.drop_table('strategy_experiment')
    op.drop_index('ix_opportunity_edge_subject', table_name='opportunity_edge')
    op.drop_index('ix_opportunity_edge_source_reference', table_name='opportunity_edge')
    op.drop_index('ix_opportunity_edge_predicate_status', table_name='opportunity_edge')
    op.drop_index('ix_opportunity_edge_object', table_name='opportunity_edge')
    op.drop_table('opportunity_edge')
    # ### end Alembic commands ###
